// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderStyle } from "./BorderStyle";
import type { Color } from "./Color";
import type { LengthUnit } from "./LengthUnit";

/**
 * Parsed `border` value.
 */
export type Border =
  | { width: LengthUnit | null; style: BorderStyle | null; color: Color | null }
  | string;
