// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderStyle } from "./BorderStyle";
import type { ColorInput } from "./ColorInput";
import type { LengthUnit } from "./LengthUnit";

/**
 * Parsed `border` value.
 */
export type Border =
  | {
      width: LengthUnit | null;
      style: BorderStyle | null;
      color: ColorInput | null;
    }
  | string;
