// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a color input value.
 */
export type ColorInput =
  | [number, number, number]
  | [number, number, number, number]
  | number
  | "currentColor"
  | string;
