// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorInput } from "./ColorInput";
import type { StopPosition } from "./StopPosition";

/**
 * Represents a gradient stop.
 */
export type GradientStop =
  | {
      /**
       * The color of the gradient stop.
       */
      color: ColorInput;
      /**
       * The position of the gradient stop.
       */
      hint?: StopPosition;
    }
  | StopPosition;
