// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundPosition } from "./BackgroundPosition";
import type { GradientStop } from "./GradientStop";
import type { RadialShape } from "./RadialShape";
import type { RadialSize } from "./RadialSize";

/**
 * Represents a radial gradient.
 */
export type RadialGradient = {
  /**
   * The radial gradient shape
   */
  shape: RadialShape;
  /**
   * The sizing mode for the gradient
   */
  size: RadialSize;
  /**
   * Center position
   */
  center: BackgroundPosition;
  /**
   * Gradient stops
   */
  stops: Array<GradientStop>;
};
